//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicAccount : SearchModel<ClinicAccount>
    {
        public int ClinicAccountId { get; set; }
        public int Income { get; set; }
        public int OutCome { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        public int DayTotalIncome { get; set; }
        public bool IsActive { get; set; }
        public int TotalIncome { get; set; }
    }
}
