//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicalAccessory:SearchModel<ClinicalAccessory>
    {
        public int AccessoriesId { get; set; }
        public string Name { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> MarketCost { get; set; }
        public string StockAmount { get; set; }
        public bool IsActive { get; set; }
    }
}
