//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClincDescription :SearchModel<ClincDescription>
    {
        public int ClinicDescriptionId { get; set; }
        public string Name { get; set; }
        public string ClinicType { get; set; }
        public string Address { get; set; }
        public string ClinicContact { get; set; }
        public string websilte { get; set; }
        public string ClinicMail { get; set; }
        public bool IsActive { get; set; }
    }
}
