//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicEstablishment:SearchModel<ClinicEstablishment>
    {
        public int EstablishmentId { get; set; }
        public int ClinicHouseCharge { get; set; }
        public int EmployeeCost { get; set; }
        public int ElectricityBill { get; set; }
        public int RowmaterialCost { get; set; }
        public int InstrumentServiceCost { get; set; }
        public int TotalCharge { get; set; }
        public int Vat { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        public bool IsActive { get; set; }

      
    }
}
