//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RowMatrial :SearchModel<RowMatrial>
    {
        public int RowMaterialId { get; set; }
        public string Name { get; set; }
        public int Cost { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime ManufacturingDate { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime ExpireDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public bool IsActive { get; set; }
    }
}
