//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;
using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;

    public partial class DrugBrand : SearchModel<DrugBrand>
    {
        public int BrandId { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Preparation { get; set; }

        public bool IsActive { get; set; }
        [Required]
        public int GenericId { get; set; }

        public virtual DrugGeneric DrugGeneric { get; set; }


    }
}
