//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseasesManagement:SearchModel<DiseasesManagement>
    {
        public int DiseasesManagementId { get; set; }
          [Required]
        [DisplayName("Management Process Name")]
        public string ManagementProcess { get; set; }
          [Required]
        [DisplayName("Prognois Status ")]
        public string Prognosis { get; set; }
        public bool IsActive { get; set; }
         [Required]

        public int DiseasesId { get; set; }
         [Required]
        public int DiseasesInvestigationId { get; set; }
         [Required]
        public int ClinicalFeatureId { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual DiseasesInvestigation DiseasesInvestigation { get; set; }
        public virtual DisesesClinicalFeature DisesesClinicalFeature { get; set; }
    }
}
