//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseasesInvestigation:SearchModel<DiseasesInvestigation>
    {
        public DiseasesInvestigation()
        {
            this.Diseases = new HashSet<Disease>();
            this.DiseasesManagements = new HashSet<DiseasesManagement>();
        }
    
        public int DiseasesInvestigationId { get; set; }
        [DisplayName("Diseases Investigation Name")]
        [Required]
        public string Name { get; set; }
           [DisplayName("Diseases Result")]
            [Required]
        public string Result { get; set; }
        public bool IsActive { get; set; }
          [Required]
        public int ClinicalFeatureId { get; set; }
    
        public virtual ICollection<Disease> Diseases { get; set; }
        public virtual DisesesClinicalFeature DisesesClinicalFeature { get; set; }
        public virtual ICollection<DiseasesManagement> DiseasesManagements { get; set; }
    }
}
