//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientShedule:SearchModel<PatientShedule>
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string PatientCode { get; set; }
        public string PataientType { get; set; }
        public System.DateTime Date { get; set; }
     
        public System.DateTime VisitingTime { get; set; }
        public string VisitingPurpose { get; set; }
        public string Contact { get; set; }
        public int serialNo { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
