//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using DENTALMIS.Utility.HelperModel;


namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Patient : SearchModel<Patient>
    {

        public Patient()
        {
            this.PatientConditions = new HashSet<PatientCondition>();
            this.PatientsMedicalHistories = new HashSet<PatientsMedicalHistory>();
            this.PaymentMethods = new HashSet<PaymentMethod>();
            this.PatientShedules = new HashSet<PatientShedule>();
        }

        public int PatientId { get; set; }
        [Required]

        public string PatientCode { get; set; }
        [Required]
      
        public  virtual string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public int Age { get; set; }
       

        [DataType(DataType.Date)]
       
        public System.DateTime VisitingtDate { get; set; }
        [Required]
        public string Contact { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public Nullable<int> SerialNumber { get; set; }
     
        [DataType(DataType.Date)]
     
        public Nullable<System.DateTime> AppionmentDate { get; set; }
      
        [DataType(DataType.Date)]
      
        public Nullable<System.DateTime> CallingDate { get; set; }
        public bool IsActive { get; set; }
        [Required]
        public int GenderId { get; set; }

        public int DiseasesId { get; set; }

        public virtual Disease Disease { get; set; }
        public virtual Gender Gender { get; set; }
       
        public virtual ICollection<PatientCondition> PatientConditions { get; set; }
        public virtual ICollection<PatientsMedicalHistory> PatientsMedicalHistories { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual ICollection<PatientShedule> PatientShedules { get; set; }
    }
}
