//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using DENTALMIS.Model;
using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;

    public partial class PaymentMethod:SearchModel<PaymentMethod>
    {
        public int PaymentMethodId { get; set; }
        [Required]
        public int PatientId { get; set; }
                [Required]
        public int DiscountAmount { get; set; }
        public int Charge { get; set; }
        public int TotalCharge { get; set; }
        public int Paid { get; set; }
        public int Due { get; set; }
        public int ServiceId { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }

        public string PaymentType { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastPaidDate { get; set; }

        public virtual Patient Patient { get; set; }
        public virtual Service Service { get; set; }
    }
}
