//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service:SearchModel<Service>
    {
        public Service()
        {
            this.PatientConditions = new HashSet<PatientCondition>();
            this.PaymentMethods = new HashSet<PaymentMethod>();
        }

        public int ServiceId { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public int TreatmentCost { get; set; }
        [Required]
        public Nullable<int> TimesOfVisit { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<PatientCondition> PatientConditions { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
    }
}
