//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;

    public partial class TodaysPatientstatu : SearchModel<TodaysPatientstatu>
    {
        public int Id { get; set; }
        [Required]
        public string PatientName { get; set; }
        [Required]
        public string PatientStatus { get; set; }
        [Required]
        public Nullable<int> SerialNo { get; set; }
        [Required]
        public String visitingtime { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime VisitingDate { get; set; }
        [Required]
        public string contact { get; set; }
        [Required]
        public string VisitingPurpose { get; set; }

        public bool IsActive { get; set; }


    }
}
