//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicEmployee:SearchModel<ClinicEmployee>
    {
        public int ClinicEmployeeId { get; set; }
        public string Name { get; set; }
        public int GenderId { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public int EmployeeDesignationId { get; set; }
        public int Salary { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employeedesignation Employeedesignation { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
