//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeedesignation:SearchModel<Employeedesignation>
    {
        public Employeedesignation()
        {
            this.ClinicEmployees = new HashSet<ClinicEmployee>();
        }
    
        public int EmployeeDesignationId { get; set; }
        public string DesinationName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ClinicEmployee> ClinicEmployees { get; set; }
    }
}
