//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DENTALMIS.Model;

namespace DENTALMIS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DENTALERPDbContext : DbContext
    {
        public DENTALERPDbContext()
            : base("name=DENTALERPDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DrugDetail> DrugDetails { get; set; }
        public virtual DbSet<DrugGeneric> DrugGenerics { get; set; }
        public virtual DbSet<DrugBrand> DrugBrands { get; set; }
        public virtual DbSet<DiseasesInvestigation> DiseasesInvestigations { get; set; }
        public virtual DbSet<DiseasesManagement> DiseasesManagements { get; set; }
        public virtual DbSet<DisesesClinicalFeature> DisesesClinicalFeatures { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<PatientsMedicalHistory> PatientsMedicalHistories { get; set; }
        public virtual DbSet<PatientCondition> PatientConditions { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<TodaysPatientstatu> TodaysPatientstatus { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DoctorsDesignation> DoctorsDesignations { get; set; }
        public virtual DbSet<ClinicEmployee> ClinicEmployees { get; set; }
        public virtual DbSet<Employeedesignation> Employeedesignations { get; set; }
        public virtual DbSet<ClincDescription> ClincDescriptions { get; set; }
        public virtual DbSet<ClinicalInstrument> ClinicalInstruments { get; set; }
        public virtual DbSet<ClinicalAccessory> ClinicalAccessories { get; set; }
        public virtual DbSet<RowMatrial> RowMatrials { get; set; }
        public virtual DbSet<ClinicAccount> ClinicAccounts { get; set; }
        public virtual DbSet<ClinicEstablishment> ClinicEstablishments { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientShedule> PatientShedules { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
    }
}
