//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using DENTALMIS.Utility.HelperModel;

namespace DENTALMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsDesignation:SearchModel<DoctorsDesignation>
    {
        public DoctorsDesignation()
        {
            this.Doctors = new HashSet<Doctor>();
        }
    
        public int DoctorDesignationId { get; set; }
       
        public string DesignationName { get; set; }
       
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}
